apiVersion: apps/v1
kind: Deployment
metadata:
  name: ostad-ui
  namespace: rahat-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ostad-ui
  template:
    metadata:
      labels:
        app: ostad-ui
    spec:
      containers:
      - name: ostad-ui
        image: your-dockerhub-username/ostad-ui:latest  # Replace with your built image
        ports:
        - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: ostad-ui
  namespace: rahat-ns
spec:
  selector:
    app: ostad-ui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5173
  type: ClusterIP